apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mymel-backend-monitor
  namespace: mymel
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: mymel-backend
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
