spring.application.name=backend

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:mymel}
spring.datasource.username=${DB_USER:mymeluser}
spring.datasource.password=${DB_PASSWORD:mymelpassword}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

# Actuator and Prometheus Metrics
management.endpoints.web.exposure.include=prometheus
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true
